### PR TITLE
Update SDO and PDO docs

### PR DESCRIPTION
**Pull request by Olavhaasie**
## Description
Updated the SDO and PDO documentation.

### CODE REVIEW

**Review by RutgerVanBeek — COMMENTED** [review]
I think this is (most of) PM-443

**Review by Joris-JW — COMMENTED** [review]
maybe nice to also reference the new SOEM interface class?

**Comment by Olavhaasie** [comment]
> maybe nice to also reference the new SOEM interface class?

I referenced the interface. What would you like to see more?

**Comment by Joris-JW** [comment]
> > maybe nice to also reference the new SOEM interface class?
> 
> I referenced the interface. What would you like to see more?

Nevermind, I thought it was not really clear we have a (kind of) wrapper for SOEM to improve the testing abilities but looking at the full docs I do think this should be enough.

**Review by Joris-JW — APPROVED** [review]

**Pull request merged**
