### PR TITLE
Add step to install ros controllers

### LINKED ISSUE #90: Creating march_ws is incomplete
Documentation needs to be added on the installation of the following packages:

### PR DESCRIPTION
**Pull request by Olavhaasie**
I have added a step in the setup of march workspace to install ros kinetic controller packages.

Closes #90.

### CODE REVIEW

**Comment by Ishadijcks** [comment]
Please use the `.. code::` directive instead of the implicit `::`

**Comment by Olavhaasie** [comment]
The other installation steps also do this. Shall I change those too?

**Comment by Ishadijcks** [comment]
Ah yes please

**Review by Ishadijcks — APPROVED** [review]
LGTM

**Pull request merged**
