### PR TITLE
Feature: reviewdog

### PR DESCRIPTION
**Pull request by Olavhaasie**
## Description
Add [reviewdog](https://github.com/reviewdog/reviewdog) GitHub checks to automatically review language and spelling.

## Changes
* Added github pr checks
* Updated `.travis.yml`

### CODE REVIEW

**Review by RutgerVanBeek — COMMENTED** [review]
Seems very nice addition to the automatic tests. What's the idea about using it? How do would one ignore something false positive and what do we do with all the thinks it found now?

**Review by Roelemans — APPROVED** [review]
Nice! I think you should add SOEM to the dictionary and ignore some files (like theme.css) haha. Can you also run reviewdog locally?

**Comment by Olavhaasie** [comment]
> Seems very nice addition to the automatic tests. What's the idea about using it? How do would one ignore something false positive and what do we do with all the thinks it found now?

The idea is that it only checks changes in PRs and the results are not required to pass. Right now it checks everything in unchanged files too, but I needed that to test the tools. Furthermore, you can just ignore false positives. 

Right now I’m trying to see what I can fix from languagetools and changing the checks to only run on changes.

**Comment by Olavhaasie** [comment]
> Nice! I think you should add SOEM to the dictionary and ignore some files haha.

I haven’t found a way to add SOEM to the dictionary of the misspell check yet. 

> Can you also run reviewdog locally?

Reviewdog is the tool that collects the warnings from tools and then posts them as a GitHub check. The actual tools used are [misspell](https://github.com/client9/misspell)and [languagetools](https://github.com/languagetool-org/languagetool)

**Review by RutgerVanBeek — APPROVED** [review]

**Pull request merged**
