### PR TITLE
Fix: theme

### PR DESCRIPTION
**Pull request by Olavhaasie**
## Description
The `sphinx-rtd-theme` was first hard copied into the `_theme` directory, which caused the theme to be outdated and making `htmlproofer` check a lot more than just our documentation. So I made it so that you have to install the `sphinx-rtd-theme`, which enables it to be updated. It can be installed from the `requirements.txt`:

    pip2 install --user -r requirements.txt

Furthermore, I moved the `override.css` to a separate `css` directory, should we ever expand that.

## Changes
* Remove hard copy of `sphinx-rtd-theme`
* Add `requirements.txt`
* Add copyright and _Last updated on_ to footer (can be useful to see how outdated the documentation is :wink:)
* Removed border on a current list item, it was very small
* Remove double quotes from `conf.py`
* A result is that the build is now 2 times faster

### CODE REVIEW

**Comment by Ishadijcks** [comment]
Can you still override the HTML of the theme now?

**Comment by Olavhaasie** [comment]
> Can you still override the HTML of the theme now?

You can override the style with `css/override.css`. The HTML is not possible I think, then you would have to create your own theme. Was the copied theme changed?

**Comment by Ishadijcks** [comment]
Yeah I think that's why we copied it but I'm not sure. @TimBuckers did we change anything about the RTD theme?

**Comment by Ishadijcks** [comment]
A quick git search shows no changes to the HTML files, so I guess it's fine

**Comment by Roelemans** [comment]
When do you need that requirement? For me this builds even without installing it

**Comment by Olavhaasie** [comment]
> When do you need that requirement? For me this builds even without installing it

Perhaps it comes as a dependency from some ROS package or you already had it installed, however, this is how it should be installed (https://sphinx-rtd-theme.readthedocs.io/en/stable/installing.html).

**Review by Roelemans — APPROVED** [review]

**Pull request merged**
